# Generated by Django 4.2.7 on 2025-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='ID Google OAuth', max_length=255, null=True, unique=True),
        ),
    ]
