# Generated by Django 4.2.7 on 2025-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
